# Generated by Django 5.2.15 on 2026-06-13 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('extraction', '0002_extractedlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('low_confidence', 'Low confidence'), ('conflict', 'Conflict'), ('missing_field', 'Missing field'), ('duplicate', 'Duplicate'), ('validation_error', 'Validation error')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='documents.balancedocument')),
                ('extracted_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_tasks', to='extraction.extractedlineitem')),
            ],
        ),
    ]
