# Generated by Django 5.2.15 on 2026-06-13 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='documents.balancedocument')),
            ],
        ),
        migrations.CreateModel(
            name='RawExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extraction_type', models.CharField(choices=[('native_text', 'Native Text'), ('ocr_text', 'OCR Text'), ('table', 'Table'), ('metadata', 'Metadata')], max_length=20)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source_method', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_extractions', to='documents.balancedocument')),
                ('processing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_extractions', to='extraction.processingrun')),
            ],
        ),
    ]
