# Generated by Django 5.2.15 on 2026-06-13 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('documents', '0001_initial'),
        ('extraction', '0001_initial'),
        ('standardization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_label', models.CharField(max_length=255)),
                ('raw_value', models.CharField(max_length=255)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], default='pending', max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_line_items', to='documents.balancedocument')),
                ('processing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_line_items', to='extraction.processingrun')),
                ('raw_extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_line_items', to='extraction.rawextraction')),
                ('reporting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_line_items', to='companies.reportingperiod')),
                ('suggested_standard_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_line_items', to='standardization.standardlineitem')),
            ],
        ),
    ]
