# Generated by Django 5.2.15 on 2026-06-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_reportingperiod_rpt_period_cmp_end_idx'),
        ('documents', '0002_balancedocument_document_status_idx_and_more'),
        ('extraction', '0003_prompttemplate_agenttask_aiextractionrun'),
        ('standardization', '0004_alter_standardlineitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedlineitem',
            name='source_account_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='source_balance_nature',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='source_hierarchy_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractedlineitem',
            name='source_parent_account_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['document', 'source_account_code'], name='ext_line_doc_code_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedlineitem',
            index=models.Index(fields=['processing_run', 'source_hierarchy_level'], name='ext_line_run_level_idx'),
        ),
    ]
