# Generated by Django 5.2.15 on 2026-06-13 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('other', 'Other')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='LineItemAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_text', models.CharField(max_length=255)),
                ('language', models.CharField(default='pt', max_length=10)),
                ('created_by_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='standardization.standardlineitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('standard_line_item', 'alias_text', 'language'), name='uniq_standard_line_alias')],
            },
        ),
    ]
