# Generated by Django 5.2.15 on 2026-06-13 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('standardization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedBalanceValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_extracted_line_item_id', models.UUIDField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=10)),
                ('approval_status', models.CharField(choices=[('approved', 'Approved'), ('superseded', 'Superseded')], default='approved', max_length=20)),
                ('approved_by_id', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_values', to='companies.company')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_values', to='companies.reportingperiod')),
                ('standard_line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standardized_values', to='standardization.standardlineitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'reporting_period', 'standard_line_item', 'approval_status'), name='uniq_active_standardized_value')],
            },
        ),
    ]
