# Generated by Django 5.2.15 on 2026-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_reportingperiod_rpt_period_cmp_end_idx'),
        ('standardization', '0002_standardizedbalancevalue'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='standardizedbalancevalue',
            index=models.Index(fields=['company', 'approval_status'], name='std_value_cmp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='standardizedbalancevalue',
            index=models.Index(fields=['reporting_period', 'standard_line_item'], name='std_value_period_line_idx'),
        ),
        migrations.AddIndex(
            model_name='standardlineitem',
            index=models.Index(fields=['category', 'sort_order'], name='std_line_cat_idx'),
        ),
    ]
