# Generated by Django 5.2.15 on 2026-06-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardization', '0003_standardizedbalancevalue_std_value_cmp_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardlineitem',
            options={'ordering': ['statement_section', 'sort_order', 'display_name']},
        ),
        migrations.AddField(
            model_name='standardizedbalancevalue',
            name='source_extracted_account_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardlineitem',
            name='display_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standardlineitem',
            name='formula',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='standardlineitem',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardlineitem',
            name='line_type',
            field=models.CharField(choices=[('detail', 'Detail'), ('subtotal', 'Subtotal'), ('total', 'Total'), ('ratio', 'Ratio')], default='detail', max_length=20),
        ),
        migrations.AddField(
            model_name='standardlineitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='standardization.standardlineitem'),
        ),
        migrations.AddField(
            model_name='standardlineitem',
            name='source_account_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='standardlineitem',
            name='statement_section',
            field=models.CharField(choices=[('balance', 'Balance'), ('liquidity', 'Liquidity')], default='balance', max_length=20),
        ),
        migrations.AddIndex(
            model_name='standardlineitem',
            index=models.Index(fields=['statement_section', 'sort_order'], name='std_line_section_idx'),
        ),
        migrations.AddIndex(
            model_name='standardlineitem',
            index=models.Index(fields=['parent', 'sort_order'], name='std_line_parent_idx'),
        ),
    ]
