# Generated by Django 5.2.15 on 2026-06-13 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('tax_identifier', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('extraction', 'Extraction')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='companies.company')),
            ],
            options={
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('company', 'alias'), name='uniq_company_alias')],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='companies.company')),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('company', 'period_label', 'currency'), name='uniq_reporting_period_for_company'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='reporting_period_end_after_start')],
            },
        ),
    ]
