# Generated by Django 5.2.15 on 2026-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportingperiod',
            index=models.Index(fields=['company', 'period_end'], name='rpt_period_cmp_end_idx'),
        ),
    ]
