# Generated by Django 5.2.15 on 2026-06-13 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='balance-documents/')),
                ('file_uri', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField()),
                ('upload_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('rejected', 'Rejected'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('detected_has_text', models.BooleanField(blank=True, null=True)),
                ('detected_language', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='companies.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
