# Generated by Django 5.2.15 on 2026-06-13 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_reportingperiod_rpt_period_cmp_end_idx'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='balancedocument',
            index=models.Index(fields=['upload_status'], name='document_status_idx'),
        ),
        migrations.AddIndex(
            model_name='balancedocument',
            index=models.Index(fields=['company', 'upload_status'], name='document_company_status_idx'),
        ),
    ]
